baseurl = ""
title = "Ivan Bueno"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = ""

[params]
    author = "Ivan Bueno"
    description = "Ivan Bueno's personal website"
    keywords = "full stack developer, drupal architect, software engineer"
    info = "FULL STACK DEVELOPER"
    avatarurl = "images/avatar.jpg"
    footercontent = ""
    fixedbarContent = "Aloha... "
    fixedbarContentAfter = "...Milky Way!"

    hideCredits = true
    hideCopyright = true

    snsShare = false

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/ivanbueno/"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/ivanbueno/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/naro143/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Ivan Bueno"

        # You can configure the theme parameter for each language.

        [languages.en.menu] # It is possible to change the menu too.

           # [[languages.en.menu.main]]
           #     name = "About"
           #     weight = 1.0
           #     url = "about"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2.0
                url = "posts"

           # [[languages.en.menu.main]]
           #     name = "Projects"
           #     weight = 3
           #     url = "projects"
           # [[languages.en.menu.main]]
           #     name = "Contact me"
           #     weight = 5
           #     url = "contact"
